# ---------------------------------------------------------------------------
# Example Configuration for the Solar Irradiance Approximation Tool
#
# INSTRUCTIONS:
# 1. Copy this file and rename it to 'config.yml' in the project root.
# 2. Replace the placeholder values below with the details of your solar park(s).
# 3. The 'config.yml' file is ignored by Git to keep your data private.
#
# The keys under 'parks' should be the human-readable names of your parks.
# ---------------------------------------------------------------------------

parks:
  # --- Park 1: Example Solar Park 1 ---
  ExampleParkA:
    # System Parameters
    system:
      # Nameplate DC Power (W) at the start of operation
      pdc0: 250000.0
      # Power temperature coefficient (%/°C). E.g., -0.0040 for -0.40%/°C.
      gamma_pmp: -0.0040
      # Nominal inverter efficiency (e.g., 0.985 for 98.5%)
      inverter_efficiency: 0.985
      # Annual degradation rate (e.g., 0.005 for 0.5% per year)
      degradation_rate: 0.005
      # The date when the park started commercial operation. Format: YYYY-MM-DD
      commissioning_date: "2020-01-01"

    # PV Module Temperature Model
    temperature_model:
      # The pvlib temperature model collection, e.g., 'sapm', 'pvsyst'
      model_type: 'sapm'
      # The specific parameter set within the model type
      model_name: 'open_rack_glass_polymer'

    # Location and Orientation
    location:
      latitude: 40.7128
      longitude: -74.0060
      # Tilt of the panels from horizontal (degrees)
      surface_tilt: 30
      # Azimuth of the panels. 180=South, 0=North.
      surface_azimuth: 180
      # Albedo (ground reflectivity), 0.2 is typical.
      albedo: 0.20

    # AC Export Limit in kilowatts (kW)
    export_limit_kw: 220.0

  # --- Park 2: Example Solar Park 2 (Optional) ---
  ExampleParkB:
    system:
      pdc0: 180000.0
      gamma_pmp: -0.0038
      inverter_efficiency: 0.980
      degradation_rate: 0.0045
      commissioning_date: "2015-01-01"
    temperature_model:
      model_type: 'pvsyst'
      model_name: 'open_rack_glass_glass'
    location:
      latitude: 34.0522
      longitude: -118.2437
      surface_tilt: 25
      surface_azimuth: 170
      albedo: 0.25
    export_limit_kw: 150.0