# ---------------------------------------------------------------------------
# Example Configuration for the Solar Irradiance Approximation Tool
#
# INSTRUCTIONS:
# 1. Copy this file and rename it to 'config.yml' in the project root.
# 2. Replace the placeholder values below with the details of your solar park(s).
# 3. The 'config.yml' file is ignored by Git to keep your data private.
#
# The keys under 'parks' should be the human-readable names of your parks.
# ---------------------------------------------------------------------------

parks:
  # --- Park 1: Example Solar Park 1 ---
  ExampleParkA:
    # System Parameters
    system:
      # Nameplate DC Power (W) at the start of operation
      pdc0: 250000.0
      # Power temperature coefficient (%/°C). E.g., -0.0040 for -0.40%/°C.
      gamma_pmp: -0.0040
      # Nominal inverter efficiency (e.g., 0.985 for 98.5%)
      inverter_efficiency: 0.985
      # DC derate factor. A catch-all for unmodeled DC losses like soiling,
      # wiring, module mismatch, etc. E.g., 0.97 for a 3% total derate.
      dc_derate_factor: 0.97
      # Annual degradation rate (e.g., 0.005 for 0.5% per year)
      degradation_rate: 0.005
      # The date when the park started commercial operation. Format: YYYY-MM-DD
      commissioning_date: "2020-01-01"

    # PV Module Temperature Model
    temperature_model:
      # The pvlib temperature model collection, e.g., 'sapm', 'pvsyst'
      model_type: 'sapm'
      # The specific parameter set within the model type
      model_name: 'open_rack_glass_polymer'

    # Location
    location:
      latitude: 40.7128
      longitude: -74.0060
      # Albedo (ground reflectivity), 0.2 is typical.
      albedo: 0.20

    # Mounting and Array Geometry
    mounting:
      # Tilt of the panels from horizontal (degrees)
      surface_tilt: 30.0
      # Azimuth of the panels. 180=South, 0=North.
      surface_azimuth: 180.0
      # Azimuth of the row's axis. For south-facing panels, rows typically
      # run East-West, so this would be 90 (East) or 270 (West).
      axis_azimuth: 90.0
      # Ground Coverage Ratio (GCR). This is the ratio of the panel's slant
      # height to the distance between rows (pitch). E.g., 0.45.
      gcr: 0.45

    # AC Export Limit in kilowatts (kW)
    export_limit_kw: 220.0

    # (Optional) Known DC Capacity Adjustments
    # Use this section to define periods where the system's DC capacity was known
    # to be different from the standard degraded nameplate capacity (pdc0). This is
    # useful for modeling periods with known issues (e.g., inverter outages, string
    # disconnections) or system upgrades/downgrades.
    # The model will apply the adjustment with the latest 'start_date' that is
    # before or on the current timestamp being processed.
    dc_capacity_adjustments:
      # Example 1: A 15% reduction in capacity for a specific period due to a
      #            temporary inverter issue.
      - start_date: "2021-06-01"
        end_date: "2021-07-15"
        adjustment_type: "percentage"
        value: -0.15 # Represents a 15% reduction from the degraded capacity

      # Example 2: A permanent 20 kW DC capacity upgrade was installed.
      #            Omitting 'end_date' means the adjustment applies indefinitely
      #            from the start_date onwards.
      - start_date: "2022-03-01"
        adjustment_type: "absolute_w"
        value: 20000.0 # Represents a 20 kW increase in capacity
      # Example 3: A period where data is known to be unreliable (e.g., SCADA
      #            system maintenance). These timestamps will be excluded from
      #            the analysis by setting their effective capacity to NaN.
      - start_date: "2023-01-10"
        end_date: "2023-01-12"
        adjustment_type: "exclude" # Can be "percentage", "absolute_w", or "exclude"
        # The 'value' key is ignored for the 'exclude' type.

  # --- Park 2: Example Solar Park 2 (Optional) ---
  ExampleParkB:
    # See the park 1 example for options.